#!/bin/bash
# Script to generate database-creation-scripts
# $Id: configure_db,v 1.7 2001/09/24 08:07:59 mohni Exp $

# prefix for tablenames
#TBL_PREFIX="phpbt_"
TBL_PREFIX=''
DB_TYPE='mysql'

#------------------------------------------------------------------------------
help() {
  echo "usage	$0 -h|--help"
  echo "	$0 [-t <db-type>] [-p <table-prefix>]"
} #end help()

#------------------------------------------------------------------------------
#parameters:
#  $TBL_PREFIX	prefix for tablenames
#  $1		filename for input
#  $2		filename for output
generate_sql() {
  cat $1 | sed "
    s/TBL_ATTACHMENT/${TBL_PREFIX}attachment/g
    s/TBL_BUG_CC/${TBL_PREFIX}bug_cc/g
    s/TBL_BUG_GROUP/${TBL_PREFIX}bug_group/g
    s/TBL_BUG_HISTORY/${TBL_PREFIX}bug_history/g
    s/TBL_BUG/${TBL_PREFIX}bug/g
    s/TBL_COMMENT/${TBL_PREFIX}comment/g
    s/TBL_COMPONENT/${TBL_PREFIX}component/g
    s/TBL_PROJECT/${TBL_PREFIX}project/g
    s/TBL_RESOLUTION/${TBL_PREFIX}resolution/g
    s/TBL_SAVED_QUERY/${TBL_PREFIX}saved_query/g
    s/TBL_SEVERITY/${TBL_PREFIX}severity/g
    s/TBL_STATUS/${TBL_PREFIX}status/g
    s/TBL_AUTH_USER/${TBL_PREFIX}auth_user/g
    s/TBL_VERSION/${TBL_PREFIX}version/g
    s/TBL_OS/${TBL_PREFIX}os/g
    s/TBL_AUTH_GROUP/${TBL_PREFIX}auth_group/g
    s/TBL_AUTH_PERM/${TBL_PREFIX}auth_perm/g
    s/TBL_USER_GROUP/${TBL_PREFIX}user_group/g
    s/TBL_USER_PERM/${TBL_PREFIX}user_perm/g
    s/TBL_GROUP_PERM/${TBL_PREFIX}group_perm/g
    s/TBL_PROJECT_GROUP/${TBL_PREFIX}project_group/g
    s/^#\ TEMPLATE:.*$/#/
    s/^--\ TEMPLATE:.*$/--/
  " > $2
} #end generate_sql()

#------------------------------------------------------------------------------
#parse commandline arguments
while [ $# -gt 0 ]; do
  case $1
  in
    '-t')		#database type
      if [ $# -gt 1 ]; then
	if [ -f schemas/$2.in ]; then	#use only if the file exists
	  DB_TYPE=$2
	else
	  echo "unknown database type $2"
	fi
	shift
      fi
      shift;;

    '-p')		#table prefix
      if [ $# -gt 1 ]; then
	TBL_PREFIX=$2
	shift
      fi
      shift;;

    '-h'|'--help')
      help
      exit 0;;

    *)			#just skip unknown options
      shift;;
  esac
done

#------------------------------------------------------------------------------
#generate SQL file
generate_sql schemas/$DB_TYPE.in createdb.sql
