create table configuration (varname char(40) not null, varvalue char(255) not null, primary key (varname));
INSERT INTO configuration VALUES ('INSTALL_URL','http://localhost/~bcurtis/phpbt','');
INSERT INTO configuration VALUES ('JPGRAPH_PATH','','If not in the include path');
INSERT INTO configuration VALUES ('CVS_WEB','http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/phpbt/phpbt/','Location of your cvs web interface (see format_comments() in bug.php)');
INSERT INTO configuration VALUES ('ADMIN_EMAIL','phpbt@bencurtis.com','');
INSERT INTO configuration VALUES ('ENCRYPT_PASS','','Whether to store passwords encrypted');
INSERT INTO configuration VALUES ('USE_JPGRAPH','','Whether to show some reports as images');
INSERT INTO configuration VALUES ('MASK_EMAIL','1','Should email addresses have . changed to \'dot\' and @ change to \'at\'?');
INSERT INTO configuration VALUES ('HIDE_EMAIL','1','Should email addresses be hidden for those not logged in?');
INSERT INTO configuration VALUES ('USE_SEVERITY_COLOR','1','Should the query list use the severity colors as the row background color (like SourceForge)');
INSERT INTO configuration VALUES ('EMAIL_IS_LOGIN','1','Whether to use email addresses as logins');
INSERT INTO configuration VALUES ('ATTACHMENT_PATH','attachments','Sub-dir of the INSTALLPATH - Needs to be writeable by the web process');
INSERT INTO configuration VALUES ('THEME','default','Which set of templates to use');
INSERT INTO configuration VALUES ('ATTACHMENT_MAX_SIZE','2097152','Maximum size (in bytes) of an attachment. This will not override the settings in php.ini if php.ini has a lower limit.');
INSERT INTO configuration VALUES ('DATE_FORMAT','m-d-Y','');
INSERT INTO configuration VALUES ('TIME_FORMAT','g:i A','');
INSERT INTO configuration VALUES ('LANGUAGE','en','');
